SELECT AUTHOR_ID, A.AUTHOR_NAME, Z.CATEGORY, Z.TOTAL_SALES 
FROM (
    SELECT AUTHOR_ID, CATEGORY, SUM(MONEY) AS TOTAL_SALES
    FROM (
        SELECT BOOK_ID, B.CATEGORY, B.AUTHOR_ID, B.PRICE * Y.SOLD AS MONEY
        FROM (
            SELECT BOOK_ID, SUM(SALES) AS SOLD
            FROM BOOK_SALES
            WHERE EXTRACT(YEAR FROM SALES_DATE) = 2022 AND EXTRACT(MONTH FROM SALES_DATE) = 1
            GROUP BY BOOK_ID
        ) Y JOIN BOOK B USING(BOOK_ID)
    )
    GROUP BY AUTHOR_ID, CATEGORY
    ORDER BY AUTHOR_ID ASC, CATEGORY DESC
) Z JOIN AUTHOR A USING(AUTHOR_ID)