SELECT U.USER_ID, U.NICKNAME, U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2 AS "전체 주소", REGEXP_REPLACE(TLNO, '(.{3})(.+)(.{4})', '\1-\2-\3') AS "전화번호" 
FROM (
SELECT WRITER_ID
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID
HAVING COUNT(BOARD_ID) >= 3
) B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC