SELECT REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, R.SCORE
FROM REST_INFO I JOIN (
    SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) R USING(REST_ID)
WHERE SUBSTR(I.ADDRESS, 0, 2) = '서울'
ORDER BY R.SCORE DESC, I.FAVORITES DESC