SELECT PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * O.SOLD AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN
(
    SELECT PRODUCT_ID, SUM(AMOUNT) AS SOLD
    FROM FOOD_ORDER
    WHERE EXTRACT(YEAR FROM PRODUCE_DATE) = 2022 AND EXTRACT(MONTH FROM PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
) O USING(PRODUCT_ID)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC