
SELECT DISTINCT CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
    USING(CAR_ID)
WHERE CAR_TYPE = '세단' AND EXTRACT(MONTH FROM HISTORY.START_DATE) = 10
ORDER BY CAR_ID DESC